spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    redis:
      url: rediss://:${REDIS_AUTH_TOKEN}@${REDIS_HOST}:6379
      timeout: ${REDIS_TIMEOUT:10s}

auth:
  jwt:
    secret: ${JWT_SECRET_KEY}
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-uri: http://localhost:8080/auth/kakao/login/callback