spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_AUTH_TOKEN}
      timeout: ${REDIS_TIMEOUT:10s}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:true}

management:
  health:
    redis:
      enabled: false

auth:
  jwt:
    secret: ${JWT_SECRET_KEY}
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-uri: http://localhost:8080/auth/kakao/login/callback
  apple:
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    private-key: ${APPLE_PRIVATE_KEY}
    redirect-uri: "https://puppy-mode.info/auth/apple/callback"

logging:
  level:
    io.lettuce.core: DEBUG
    io.lettuce.core.protocol: DEBUG
    io.netty: INFO